[package]
name = "kataglyphis-rustprojecttemplate"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
anyhow = "1"
log = "0.4"
env_logger = "0.11.8"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
