name: Rust workflow on Windows 2025
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows-pipeline:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message || '', '[build-win]') }}
    name: Build, test, and package (windows-2025)
    runs-on: windows-2025
    env:
      BINARY: kataglyphis-rustprojecttemplate
      VERSION: ${{ github.ref_name }}
    
    steps:
      - name: Enable Git long paths
        run: git config --global core.longpaths true
        shell: pwsh

      - name: 📥 Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cleanup disk space
        uses: ./.github/actions/cleanup-disk-space

      - name: Login to GitHub
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: Kataglyphis
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull image
        run: |
          docker pull ghcr.io/kataglyphis/kataglyphis_beschleuniger:winamd64 

      - name: Run build inside container
        shell: pwsh
        run: |
          # 1. Define the script exactly as you want it to run inside the container
          $script = @'
          $ErrorActionPreference = "Stop"
          Write-Host "Starting Build Process..."
          rustup component add rustfmt
          cargo fmt --all -- --check
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --all --verbose
          cargo bench
          cargo build --release
          '@

          # 2. Base64 encode the script to avoid quoting/newline issues in Docker arguments
          $bytes = [System.Text.Encoding]::Unicode.GetBytes($script)
          $encodedCommand = [Convert]::ToBase64String($bytes)

          # 3. Run Docker with EncodedCommand
          docker run --rm `
            --env BINARY="${{ env.BINARY }}" `
            --env VERSION="${{ env.VERSION }}" `
            --mount "type=bind,source=${{ github.workspace }},target=C:\workspace" `
            -w "C:\workspace" `
            ghcr.io/kataglyphis/kataglyphis_beschleuniger:winamd64 `
            powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand $encodedCommand

      - name: 📦 Prepare archive variables
        id: vars
        shell: pwsh
        run: |
          $archive = "$env:BINARY-$env:VERSION-windows-2025-x64.zip"
          echo "archive_name=$archive" >> $env:GITHUB_OUTPUT

      - name: 📦 Create archive
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Compress-Archive -Path "target/release/$env:BINARY.exe" -DestinationPath "dist/${{ steps.vars.outputs.archive_name }}" -Force

      - name: 📤 Upload build artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{ env.BINARY }}-${{ github.ref_name }}-windows-2025-x64
          path: dist/${{ steps.vars.outputs.archive_name }}
