name: Rust workflow on Windows 2025

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-2025

  test:
    uses: ./.github/workflows/test.yml
    with:
      runner: windows-2025
        
