# .github/workflows/rust-build.yml
name: Build app

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  build-app:
    name: Build app
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Equivalent of .common_steps_per_job_on_linux
      - name: Debug build
        run: |
          cd kataglyphis-rustprojecttemplate
          cargo build --verbose
