name: Rust workflow on Ubuntu-24.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
    
    - name: Build
      run: |
        cd kataglyphis-rustprojecttemplate
        cargo build --verbose

    - name: Run tests
      run: |
        cd kataglyphis-rustprojecttemplate
        cargo test --verbose
