# .github/workflows/test.yml
name: Build app

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  build-app:
    name: Testing
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cd kataglyphis-rustprojecttemplate
          cargo test --verbose
